# Generated by Django 5.2.16 on 2026-08-01 14:38

import apps.accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.TextField(blank=True, default='')),
                ('email_verified_at', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.TextField()),
                ('email', models.TextField(blank=True, default='')),
                ('created_at', models.TextField()),
                ('created_by', models.TextField(blank=True, default='')),
                ('is_super', models.IntegerField(default=0)),
                ('admin_level', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'admin_accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('purpose', models.TextField()),
                ('code_hash', models.TextField()),
                ('request_ip', models.TextField(blank=True, default='')),
                ('attempt_count', models.IntegerField(default=0)),
                ('created_at', models.TextField()),
                ('expires_at', models.TextField()),
                ('used_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_verification_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminRegisterToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('created_by', models.TextField()),
                ('created_at', models.TextField()),
                ('admin_level', models.IntegerField(default=1)),
                ('used_at', models.TextField(blank=True, null=True)),
                ('used_by_admin', models.ForeignKey(blank=True, db_column='used_by_admin_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_register_tokens', to='accounts.adminaccount')),
            ],
            options={
                'db_table': 'admin_register_tokens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LegacySession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('role', models.TextField()),
                ('username', models.TextField()),
                ('admin_level', models.IntegerField(blank=True, null=True)),
                ('is_super', models.IntegerField(default=0)),
                ('created_ip', models.TextField(blank=True, null=True)),
                ('last_seen_ip', models.TextField(blank=True, null=True)),
                ('exp', models.FloatField()),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legacy_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('channel', models.TextField(default='email')),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'subscribers',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('email', 'channel'), name='uq_subscribers_email_channel')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.TextField()),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
                'managed': True,
            },
        ),
    ]
