# Generated by Django 5.2.16 on 2026-08-01 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0002_legacy_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('cover_url', models.TextField(blank=True, default='')),
                ('points_cost', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '上架'), ('archived', '下架')], default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='store_product_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_ciphertext', models.TextField()),
                ('code_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('available', '可兑换'), ('redeemed', '已兑换'), ('revoked', '已撤销')], default='available', max_length=20)),
                ('imported_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='store.storeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_cost', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('fulfilled', '已发放'), ('revoked', '已撤销')], default='fulfilled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='store.storecode')),
                ('point_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_redemptions', to='points.pointledger')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='store.storeproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='storecode',
            index=models.Index(fields=['product', 'status'], name='store_code_stock_idx'),
        ),
        migrations.AddConstraint(
            model_name='storecode',
            constraint=models.UniqueConstraint(fields=('product', 'code_digest'), name='uq_store_product_code_digest'),
        ),
        migrations.AddConstraint(
            model_name='storeredemption',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'id'), name='uq_store_redemption_identity'),
        ),
    ]
