# Generated by Django 5.2.16 on 2026-09-12 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_storeredemption_uq_store_redemption_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_username', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_url', models.CharField(blank=True, default='', max_length=500)),
                ('price_points', models.PositiveIntegerField(default=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('deliverable_type', models.CharField(choices=[('text', '文本说明'), ('code', '兑换码'), ('link', '外部链接')], default='text', max_length=16)),
                ('deliverable_text', models.TextField(blank=True, default='')),
                ('deliverable_codes', models.TextField(blank=True, default='')),
                ('deliverable_link', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '在售'), ('rejected', '已驳回'), ('off_shelf', '已下架')], default='draft', max_length=20)),
                ('review_reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store_listings',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='store_listing_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_username', models.CharField(max_length=150)),
                ('seller_username', models.CharField(max_length=150)),
                ('points_paid', models.PositiveIntegerField(default=0)),
                ('seller_earning', models.PositiveIntegerField(default=0)),
                ('delivered_payload', models.TextField()),
                ('buyer_ledger_id', models.IntegerField(default=0)),
                ('seller_ledger_id', models.IntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_redemptions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='store.storelisting')),
            ],
            options={
                'db_table': 'listing_redemptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
