# Generated by Django 5.2.16 on 2026-08-01 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAccount',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='point_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField(default=0)),
                ('total_earned', models.IntegerField(default=0)),
                ('total_spent', models.IntegerField(default=0)),
                ('contribution_score', models.IntegerField(default=0)),
                ('reputation_level', models.IntegerField(default=0)),
                ('consecutive_active_days', models.IntegerField(default=0)),
                ('last_active_date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='active')),
                ('updated_at', models.TextField()),
            ],
            options={
                'db_table': 'point_accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.TextField()),
                ('delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('contribution_delta', models.IntegerField(default=0)),
                ('reference_type', models.TextField(blank=True, default='')),
                ('reference_id', models.TextField(blank=True, default='')),
                ('idempotency_key', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.TextField(default='settled')),
                ('available_at', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(default='system')),
                ('created_at', models.TextField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='point_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'point_ledger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserDailyActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.TextField()),
                ('created_at', models.TextField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_daily_activity',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_date'), name='uq_daily_activity_user_date')],
            },
        ),
    ]
