# Generated by Django 5.2.16 on 2026-08-01 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '交易中'), ('paused', '已暂停'), ('settling', '结算中'), ('closed', '已结束')], default='draft', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('seed', models.PositiveBigIntegerField(default=1)),
                ('fee_bps', models.PositiveIntegerField(default=200)),
                ('spread_bps', models.PositiveIntegerField(default=300)),
                ('max_order_points', models.PositiveIntegerField(default=100)),
                ('daily_user_stake_limit', models.PositiveIntegerField(default=500)),
                ('daily_user_orders_limit', models.PositiveIntegerField(default=20)),
                ('daily_user_payout_limit', models.PositiveIntegerField(default=1000)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('max_position_shares', models.PositiveIntegerField(default=100)),
                ('max_profit_bps', models.PositiveIntegerField(default=1000)),
                ('bot_initial_cash', models.PositiveIntegerField(default=0)),
                ('bot_cash_balance', models.PositiveIntegerField(default=0)),
                ('bot_max_loss', models.PositiveIntegerField(default=0)),
                ('bot_daily_payout_limit', models.PositiveIntegerField(default=0)),
                ('bot_daily_payout_used', models.PositiveIntegerField(default=0)),
                ('reserved_payout_points', models.PositiveIntegerField(default=0)),
                ('pause_reason', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
                'indexes': [models.Index(fields=['status', 'starts_at', 'ends_at'], name='market_round_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketTreasuryLedger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('seed', 'seed'), ('admin_fund', 'admin_fund'), ('buy_in', 'buy_in'), ('sell_payout', 'sell_payout'), ('fee_burn', 'fee_burn'), ('settlement', 'settlement')], max_length=30)),
                ('delta', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField()),
                ('fee_points', models.PositiveIntegerField(default=0)),
                ('reference_id', models.CharField(blank=True, default='', max_length=160)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_ledger', to='market.marketround')),
            ],
        ),
        migrations.CreateModel(
            name='MarketQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.PositiveBigIntegerField()),
                ('mid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ask_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='market.marketasset')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='market.marketround')),
            ],
            options={
                'indexes': [models.Index(fields=['round', 'asset', '-bucket'], name='market_quote_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('round', 'asset', 'bucket'), name='uq_market_round_asset_bucket')],
            },
        ),
        migrations.CreateModel(
            name='MarketPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invested_points', models.PositiveIntegerField(default=0)),
                ('reserved_payout_points', models.PositiveIntegerField(default=0)),
                ('realized_points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', '持仓中'), ('closed', '已平仓')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='market.marketasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_positions', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='market.marketround')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'round', 'status'], name='market_user_round_position_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'round', 'asset'), name='uq_market_user_round_asset')],
            },
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_points', models.PositiveIntegerField()),
                ('fee_points', models.PositiveIntegerField(default=0)),
                ('net_points', models.IntegerField()),
                ('status', models.CharField(choices=[('filled', '成交'), ('rejected', '拒绝')], default='filled', max_length=20)),
                ('source', models.CharField(choices=[('user', '用户下单'), ('settlement', '轮次结算')], default='user', max_length=20)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.marketasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_orders', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.marketround')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'round', '-created_at'], name='market_user_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketDailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('stake_points', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('payout_points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_daily_usage', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='market.marketround')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'round', 'activity_date'), name='uq_market_user_round_date')],
            },
        ),
        migrations.CreateModel(
            name='MarketBotInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_shares', models.PositiveIntegerField(default=0)),
                ('shares_available', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bot_inventory', to='market.marketasset')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_inventory', to='market.marketround')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'asset'), name='uq_market_round_asset_inventory')],
            },
        ),
        migrations.CreateModel(
            name='MarketBotDailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('payout_points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_daily_usage', to='market.marketround')),
            ],
            options={
                'indexes': [models.Index(fields=['round', 'activity_date'], name='market_bot_usage_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('round', 'activity_date'), name='uq_market_bot_round_date')],
            },
        ),
        migrations.CreateModel(
            name='MarketAdminAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=150)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audits', to='market.marketround')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['round', '-created_at'], name='market_audit_round_idx')],
            },
        ),
    ]
