# Generated by Django 5.2.16 on 2026-09-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('status', models.CharField(default='running', max_length=16)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crawl_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=190)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=500)),
                ('author', models.CharField(blank=True, default='', max_length=190)),
                ('language', models.CharField(blank=True, default='', max_length=64)),
                ('metrics', models.TextField(blank=True, default='')),
                ('heat_score', models.FloatField(db_index=True, default=0)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_crawled_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'external_projects',
                'ordering': ['-heat_score', '-votes', '-id'],
                'indexes': [models.Index(fields=['is_active', '-heat_score'], name='external_pr_is_acti_937922_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uq_external_project_source_id')],
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes_detail', to='rankings.externalproject')),
            ],
            options={
                'db_table': 'external_project_votes',
                'constraints': [models.UniqueConstraint(fields=('project', 'username'), name='uq_external_vote_user')],
            },
        ),
    ]
