# Generated by Django 5.2.16 on 2026-09-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproject',
            name='analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='externalproject',
            name='analysis_source',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='externalproject',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalproject',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='externalproject',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='externalproject',
            name='trend_state',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.CreateModel(
            name='ExternalMetricLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('heat', models.FloatField(default=0)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('replies', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='metric_logs', to='rankings.externalproject')),
            ],
            options={
                'db_table': 'external_metric_logs',
                'ordering': ['captured_at'],
                'indexes': [models.Index(fields=['project', 'captured_at'], name='external_me_project_5da323_idx')],
            },
        ),
    ]
