# Generated by Django 5.2.16 on 2026-09-12 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_avatar_url_user_bio_user_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(default='star', max_length=32)),
                ('tier', models.CharField(choices=[('bronze', '铜'), ('silver', '银'), ('gold', '金')], default='bronze', max_length=8)),
                ('category', models.CharField(choices=[('creation', '创作'), ('interaction', '互动'), ('activity', '活跃'), ('business', '商务')], default='interaction', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='community_stats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('topics', models.PositiveIntegerField(default=0)),
                ('replies', models.PositiveIntegerField(default=0)),
                ('likes_given', models.PositiveIntegerField(default=0)),
                ('likes_received', models.PositiveIntegerField(default=0)),
                ('reply_likes_received', models.PositiveIntegerField(default=0)),
                ('votes_cast', models.PositiveIntegerField(default=0)),
                ('boosts_bought', models.PositiveIntegerField(default=0)),
                ('listings_sold', models.PositiveIntegerField(default=0)),
                ('max_topic_likes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_by', models.CharField(default='system', max_length=150)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='gamification.achievement')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ['-granted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='uq_user_achievement')],
            },
        ),
    ]
