# Generated by Django 5.2.16 on 2026-09-13 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='showcase',
            field=models.ForeignKey(blank=True, db_column='showcase_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcased_by', to='gamification.achievement'),
        ),
    ]
