# Generated by Django 5.2.16 on 2026-08-01 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadEntitlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('cost', models.IntegerField(default=0)),
                ('remaining_count', models.IntegerField(default=1)),
                ('idempotency_key', models.TextField(unique=True)),
                ('created_at', models.TextField()),
                ('expires_at', models.TextField(blank=True, null=True)),
                ('consumed_at', models.TextField(blank=True, null=True)),
                ('point_ledger', models.ForeignKey(blank=True, db_column='point_ledger_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_entitlements', to='points.pointledger')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_entitlements', to='catalog.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'download_entitlements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.TextField(default='pending')),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.TextField()),
                ('reviewed_at', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.TextField(blank=True, null=True)),
                ('consumed_at', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_requests', to='catalog.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='download_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'download_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('downloaded_at', models.TextField()),
                ('ip', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='downloads', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='downloads', to=settings.AUTH_USER_MODEL)),
                ('entitlement', models.ForeignKey(blank=True, db_column='entitlement_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='downloads', to='downloads.downloadentitlement')),
                ('request', models.ForeignKey(blank=True, db_column='request_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='downloads', to='downloads.downloadrequest')),
            ],
            options={
                'db_table': 'downloads',
                'managed': True,
            },
        ),
    ]
