# Generated by Django 5.2.16 on 2026-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_legacy_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_id', models.TextField(unique=True)),
                ('product_id', models.IntegerField()),
                ('username', models.TextField()),
                ('level', models.IntegerField()),
                ('original', models.TextField()),
                ('size', models.BigIntegerField()),
                ('count', models.IntegerField()),
                ('platform', models.TextField()),
                ('architecture', models.TextField()),
                ('expires_at', models.FloatField()),
                ('written', models.BigIntegerField(default=0)),
                ('expected_sha256', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'django_upload_sessions',
                'managed': True,
            },
        ),
    ]
