# Generated by Django 5.2.16 on 2026-08-01 18:17

import apps.imaging.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0002_legacy_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('size', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=20)),
                ('output_format', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='queued', max_length=20)),
                ('points_cost', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('image', models.FileField(blank=True, upload_to=apps.imaging.models.image_upload_to)),
                ('image_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_generation_jobs', to='points.pointledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='imaging_user_created_idx'), models.Index(fields=['status', 'created_at'], name='imaging_status_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uq_imaging_user_idempotency')],
            },
        ),
    ]
