# pyright: reportMissingImports=false, reportMissingModuleSource=false
# Generated by Django 5.2.16 on 2026-09-03 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_imaging_provider_pool'),
        ('points', '0002_legacy_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerationjob',
            name='cache_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='cache_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='cache_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cache_copies', to='imaging.imagegenerationjob'),
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='original_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagegenerationjob',
            name='stored_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='imagegenerationjob',
            index=models.Index(fields=['user', 'cache_key', 'status', '-completed_at'], name='imaging_cache_lookup_idx'),
        ),
    ]
