# Generated by Django 5.2.17 on 2026-09-14 15:42

import apps.imaging.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0003_imagegenerationjob_cache_hit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegenerationjob",
            name="original_image",
            field=models.FileField(
                blank=True,
                storage=apps.imaging.storage.OriginalImageStorage(),
                upload_to=apps.imaging.storage.original_upload_to,
            ),
        ),
    ]
