# Generated by Django 5.2.17 on 2026-09-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0008_imagegenerationreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingtemplate',
            name='skill_entrypoint',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='imagingtemplate',
            name='skill_files',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='imagingtemplate',
            name='skill_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='imagingtemplate',
            name='skill_revision',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='imagingtemplate',
            name='skill_source_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
