# Generated by Django 5.2.16 on 2026-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120)),
                ('en', models.CharField(blank=True, default='', max_length=120)),
                ('definition', models.TextField()),
                ('category', models.CharField(default='基础概念', max_length=32)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'glossary_terms',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('content_md', models.TextField()),
                ('difficulty', models.CharField(default='beginner', max_length=16)),
                ('kind', models.CharField(default='tutorial', max_length=16)),
                ('series', models.CharField(blank=True, default='', max_length=120)),
                ('cover_url', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.CharField(blank=True, default='', max_length=256)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tutorials',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
