# Generated by Django 5.2.16 on 2026-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryterm',
            name='content_md',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='slug',
            field=models.SlugField(default='', max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
