# Generated by Django 5.2.16 on 2026-09-12 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_glossaryterm_content_md_glossaryterm_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=12)),
                ('slug', models.SlugField(max_length=140)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='learn_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learn_progress',
                'indexes': [models.Index(fields=['user', 'kind'], name='learn_progr_user_id_89dce6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'slug'), name='uq_learn_progress')],
            },
        ),
    ]
