# Generated by Django 5.2.16 on 2026-08-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeleteRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, default='')),
                ('product_slug', models.TextField(blank=True, default='')),
                ('requested_by', models.TextField()),
                ('requester_level', models.IntegerField()),
                ('owner_username', models.TextField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.TextField(default='pending')),
                ('created_at', models.TextField()),
                ('decided_at', models.TextField(blank=True, null=True)),
                ('decided_by', models.TextField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='delete_requests', to='catalog.product')),
            ],
            options={
                'db_table': 'product_delete_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PublishRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_by', models.TextField()),
                ('requester_level', models.IntegerField()),
                ('reviewer_scope', models.TextField()),
                ('reviewer_pool_count', models.IntegerField()),
                ('reviewer_pool_weight', models.IntegerField(default=0)),
                ('approve_threshold_weight', models.IntegerField(default=0)),
                ('status', models.TextField(default='pending')),
                ('created_at', models.TextField()),
                ('expires_at', models.TextField(blank=True, null=True)),
                ('decided_at', models.TextField(blank=True, null=True)),
                ('decided_note', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='publish_requests', to='catalog.product')),
            ],
            options={
                'db_table': 'publish_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PublishRequestVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_username', models.TextField()),
                ('reviewer_level', models.IntegerField()),
                ('vote', models.TextField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.TextField()),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='publishing.publishrequest')),
            ],
            options={
                'db_table': 'publish_request_votes',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('request', 'reviewer_username'), name='uq_publish_vote_request_reviewer')],
            },
        ),
    ]
