#!/usr/bin/env python3
"""
Fix-import script: reads export.sql (generated by Python repr()),
properly handles Python-style escaping, and inserts into the database.
"""
import ast
import os
import re
import sqlite3
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, "data", "homepage.db")


def replace_null_outside_quotes(text):
    """Replace NULL with None, but only outside single-quoted strings."""
    parts = text.split("'")
    result_parts = []
    for i, part in enumerate(parts):
        if i % 2 == 0:  # outside quotes
            part = re.sub(r"\bNULL\b", "None", part)
        result_parts.append(part)
    return "'".join(result_parts)


def parse_values(values_str: str) -> tuple | None:
    """Parse SQL VALUES tuple that was generated by Python repr()."""
    # Python repr() wraps strings in single quotes, and uses \' for embedded single quotes
    # We need to replace NULL with None first for ast.literal_eval
    # But only NULL that's not inside quotes
    cleaned = replace_null_outside_quotes(values_str)
    # Wrap in parentheses for ast.literal_eval
    try:
        result = ast.literal_eval("(" + cleaned + ")")
        if isinstance(result, tuple):
            return result
        return (result,)
    except (SyntaxError, ValueError) as exc:
        print(f"  Failed to parse values: {exc}")
        print(f"  Values preview: {values_str[:200]}")
        return None


def sql_escape(value) -> str:
    """Convert a Python value to a proper SQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, str):
        # SQL escape: double single quotes
        escaped = value.replace("'", "''")
        return f"'{escaped}'"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return repr(value)
    return repr(value)


def fix_and_rebuild(export_path: str) -> None:
    """Rebuild the database from the export SQL with proper escaping."""
    if not os.path.exists(export_path):
        print(f"❌ 文件不存在: {export_path}")
        sys.exit(1)

    with open(export_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    conn = sqlite3.connect(DB_PATH)

    # Collect all INSERT and DELETE statements, rebuild them properly
    # We need to read line by line, because the original may have multi-line values
    # (the old export joined all DELETE/INSERT into one line each, so it should be OK)

    sql_statements = []
    current_insert = []
    in_insert = False

    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("--"):
            if in_insert:
                # Rebuild the multi-line INSERT
                full_sql = " ".join(current_insert)
                # Remove any actual newlines embedded in the values
                full_sql = full_sql.replace("\n", " ").replace("\r", "")
                # Clean up multiple spaces
                while "  " in full_sql:
                    full_sql = full_sql.replace("  ", " ")
                
                table_name = None
                for t in ["products", "product_versions", "downloads", "download_requests",
                          "users", "admin_accounts", "admin_register_tokens",
                          "admin_upload_events", "publish_requests", "publish_request_votes",
                          "product_delete_requests", "subscribers", "user_subscriptions"]:
                    if f'"{t}"' in full_sql:
                        table_name = t
                        break
                
                if table_name and full_sql.startswith("DELETE FROM"):
                    sql_statements.append(full_sql)
                elif table_name and full_sql.startswith("INSERT INTO"):
                    sql_statements.append(full_sql)
                
                current_insert = []
                in_insert = False
            continue
        
        if stripped.startswith("DELETE FROM") or stripped.startswith("INSERT INTO"):
            if in_insert:
                # Save previous
                full_sql = " ".join(current_insert)
                full_sql = full_sql.replace("\n", " ").replace("\r", "")
                while "  " in full_sql:
                    full_sql = full_sql.replace("  ", " ")
                sql_statements.append(full_sql)
            
            current_insert = [stripped]
            in_insert = True
        elif in_insert:
            current_insert.append(stripped)

    # Don't forget the last one
    if current_insert:
        full_sql = " ".join(current_insert)
        full_sql = full_sql.replace("\n", " ").replace("\r", "")
        while "  " in full_sql:
            full_sql = full_sql.replace("  ", " ")
        sql_statements.append(full_sql)

    print(f"Found {len(sql_statements)} SQL statements to process")

    # Now rebuild each INSERT with proper SQL escaping
    fixed_count = 0
    for sql in sql_statements:
        if sql.startswith("DELETE FROM"):
            try:
                conn.execute(sql)
                conn.commit()
            except Exception as e:
                print(f"  DELETE failed: {e}")
            continue

        if not sql.startswith("INSERT INTO"):
            continue

        # Parse: INSERT INTO "table" (col1, col2) VALUES (val1, val2);
        try:
            # Find VALUES
            values_idx = sql.find(" VALUES (")
            if values_idx < 0:
                print(f"  No VALUES found, skipping: {sql[:80]}...")
                continue

            columns_part = sql[:values_idx]
            values_str = sql[values_idx + len(" VALUES (") :]
            # Remove trailing semicolon and closing paren
            if values_str.endswith(";"):
                values_str = values_str[:-1]
            if values_str.endswith(")"):
                values_str = values_str[:-1]

            # Parse values as Python tuple
            values = parse_values(values_str)
            if values is None:
                # Try wrapping in parens for literal_eval
                values = parse_values("(" + values_str + ")")
            if values is None:
                print(f"  Skipping: {columns_part[:60]}...")
                continue

            if not isinstance(values, (list, tuple)):
                print(f"  Values not a tuple: {type(values)}")
                continue

            # Rebuild with proper SQL escaping
            escaped_vals = [sql_escape(v) for v in values]
            fixed_sql = f"{columns_part} VALUES ({', '.join(escaped_vals)});"

            conn.execute(fixed_sql)
            conn.commit()
            fixed_count += 1

        except Exception as e:
            print(f"  Failed: {e}")
            print(f"  SQL: {sql[:120]}...")
            continue

    conn.close()
    print(f"✅ 成功处理 {fixed_count} 条 INSERT 语句")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        fix_and_rebuild(sys.argv[1])
    else:
        fix_and_rebuild(os.path.join(BASE_DIR, "data", "export.sql"))
