# Generated by Django 5.2.16 on 2026-08-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.TextField(blank=True, default='')),
                ('platforms', models.TextField(default='[]')),
                ('architectures', models.TextField(default='[]')),
                ('tags', models.TextField(blank=True, default='')),
                ('announcement', models.TextField(blank=True, default='')),
                ('version', models.TextField(default='0.1.0')),
                ('changelog', models.TextField(blank=True, default='')),
                ('status', models.TextField(default='draft')),
                ('created_by', models.TextField(blank=True, default='')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_sha256', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('published_at', models.TextField(blank=True, null=True)),
                ('point_download_cost', models.IntegerField(blank=True, null=True)),
                ('points_redemption_enabled', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_key', models.TextField(primary_key=True, serialize=False)),
                ('setting_value', models.TextField(blank=True, default='')),
                ('updated_at', models.TextField(blank=True, default='')),
                ('updated_by', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'system_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.TextField(blank=True, null=True)),
                ('architecture', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_sha256', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='packages', to='catalog.product')),
            ],
            options={
                'db_table': 'product_packages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField()),
                ('category', models.TextField(blank=True, default='')),
                ('platforms', models.TextField(default='[]')),
                ('architectures', models.TextField(default='[]')),
                ('tags', models.TextField(blank=True, default='')),
                ('announcement', models.TextField(blank=True, default='')),
                ('version', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('changelog', models.TextField(blank=True, default='')),
                ('status', models.TextField(default='draft')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_sha256', models.TextField(blank=True, null=True)),
                ('published_at', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('created_by', models.TextField(blank=True, default='')),
                ('source', models.TextField(default='snapshot')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='catalog.product')),
            ],
            options={
                'db_table': 'product_versions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminUploadEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.TextField()),
                ('uploaded_at', models.TextField()),
                ('file_size', models.IntegerField(default=0)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_upload_events', to='catalog.product')),
            ],
            options={
                'db_table': 'admin_upload_events',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('admin_username', 'product'), name='uq_admin_upload_admin_product')],
            },
        ),
    ]
