# pyright: reportMissingImports=false
# typos: ignore[unknown]
# Generated by Django 5.2.16 on 2026-09-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_seed_forum_data'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # typos: ignore[unknown]
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX IF NOT EXISTS forum_topic_categor_00de6c_idx
                        ON forum_topics (category_id, status, created_at DESC);
                        DROP INDEX IF EXISTS forum_topic_category_status_created_idx;
                    """,
                    reverse_sql="""
                        CREATE INDEX IF NOT EXISTS forum_topic_category_status_created_idx
                        ON forum_topics (category_id, status, created_at DESC);
                        DROP INDEX IF EXISTS forum_topic_categor_00de6c_idx;
                    """,
                ),
            ],
            # typos: ignore[unknown]
            state_operations=[
                migrations.RenameIndex(
                    model_name="forumtopic",
                    new_name="forum_topic_categor_00de6c_idx",
                    old_name="forum_topic_category_status_created_idx",
                ),
            ],
        ),
    ]
