# Generated by Django 5.2.16 on 2026-09-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_forum_topic_category_status_created_idx_forum_topic_categor_00de6c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_username', models.CharField(max_length=150)),
                ('file', models.FileField(max_length=300, upload_to='forum/%Y/%m/')),
                ('content_type', models.CharField(default='image/jpeg', max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum_images',
            },
        ),
        migrations.CreateModel(
            name='ForumReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum_reply_likes',
            },
        ),
        migrations.CreateModel(
            name='ForumTopicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('link_type', models.CharField(default='other', max_length=16)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum_topic_links',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('tier', models.CharField(default='small', max_length=16)),
                ('points_cost', models.PositiveIntegerField(default=0)),
                ('boost_score', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(default='active', max_length=16)),
                ('ledger_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum_topic_boosts',
            },
        ),
        migrations.CreateModel(
            name='TopicViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_key', models.CharField(max_length=180)),
                ('view_date', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum_topic_view_logs',
            },
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='dedup_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='hot_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='images',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['status', '-hot_score'], name='forum_topic_status_824ba7_idx'),
        ),
        migrations.AddField(
            model_name='forumreplylike',
            name='reply',
            field=models.ForeignKey(db_column='reply_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.forumreply'),
        ),
        migrations.AddField(
            model_name='forumtopiclink',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='forum.forumtopic'),
        ),
        migrations.AddField(
            model_name='topicboost',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='forum.forumtopic'),
        ),
        migrations.AddField(
            model_name='topicviewlog',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='forum.forumtopic'),
        ),
        migrations.AddConstraint(
            model_name='forumreplylike',
            constraint=models.UniqueConstraint(fields=('reply', 'username'), name='uq_forum_reply_like_user'),
        ),
        migrations.AddConstraint(
            model_name='forumtopiclink',
            constraint=models.UniqueConstraint(fields=('topic', 'url'), name='uq_topic_link_url'),
        ),
        migrations.AddIndex(
            model_name='topicboost',
            index=models.Index(fields=['status', 'ends_at'], name='forum_topic_status_cd13f5_idx'),
        ),
        migrations.AddIndex(
            model_name='topicviewlog',
            index=models.Index(fields=['topic', 'view_date'], name='forum_topic_topic_i_ae6c8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicviewlog',
            constraint=models.UniqueConstraint(fields=('topic', 'viewer_key', 'view_date'), name='uq_topic_view_daily'),
        ),
    ]
