# Generated by Django migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0005_forumreport_forummoderationaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumcategory",
            name="moderators",
            field=models.ManyToManyField(
                blank=True,
                related_name="moderated_forum_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
