# Generated by Django 5.2.16 on 2026-09-12 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('badge', '成就勋章'), ('level', '等级提升'), ('like', '收到点赞'), ('reply', '收到评论'), ('reply_like', '评论被赞'), ('sale', '商品售出'), ('system', '系统通知')], default='system', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, default='', max_length=300)),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
